"""calculation_classes

Revision ID: 8b40e241a0d5
Revises: 7a63f689a3f2
Create Date: 2025-04-19 00:12:02.027386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b40e241a0d5'
down_revision: Union[str, None] = '7a63f689a3f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.create_table("user")
    op.add_column("user", sa.Column("id", sa.INTEGER(), nullable=False, primary_key=True, index=True))
    op.add_column("user", sa.Column("name", sa.VARCHAR(), nullable=False, index=True, unique=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
