"""calculation classes

Revision ID: 7d6601a132e0
Revises:
Create Date: 2025-04-12 18:55:11.178938

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7d6601a132e0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # ### end Alembic commands ###
    op.create_table("user")
    op.add_column("user", sa.Column("id", sa.INTEGER(), nullable=False, primary_key=True, index=True))
    op.add_column("user", sa.Column("name", sa.VARCHAR(), nullable=False, index=True, unique=True))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user")
    # ### end Alembic commands ###
